version: '3'
services:
    model:
        build: .
        container_name: cleaner
        volumes:
            - ./:/home/jovyan/work
        ports:
            - 6006:6006
            - 8888:8888
        # runtime: nvidia
        environment:
            DEBUG: 1
