version: '3'
services:
    model:
        build: .
        container_name: rnn_ecqq
        volumes:
            - ./:/tf/ecqq
        ports:
            - 6006:6006
            - 8888:8888
        # runtime: nvidia
        environment:
            DEBUG: 1
